targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/features/admin/data/models/**/*.dart
            - lib/features/bilanCarbone/data/models/**.dart
            - lib/core/domain/entities/**.dart
      json_serializable:
        generate_for:
          include:
            - lib/features/admin/data/models/**/*.dart
            - lib/features/bilanCarbone/data/models/**.dart
            - lib/core/domain/entities/**.dart
